version: '3.9'
services:
  php:
    image: touch4it/yii2-php-fpm-nginx:7.4-dev 
    depends_on:
      - mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - .:/var/www/html
    ports:
      - '8000:80'
  mysql:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2basic
      - MYSQL_USER=yii2basic
      - MYSQL_PASSWORD=secret
    volumes:
      - ./db/data:/var/lib/mysql
