version: '3.9'
services:
  php:
    image: touch4it/yii2-php-fpm-nginx:7.4-dev 
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - .:/var/www/html
    ports:
      - '8000:80'
